// <auto-generated />
using System;
using AlexDuzik.ProfileSite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlexDuzik.ProfileSite.Data.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20220828011816_Permalink required")]
    partial class Permalinkrequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("AlexDuzik.ProfileSite.Web.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("AlexDuzik.ProfileSite.Web.Post", b =>
                {
                    b.OwnsOne("AlexDuzik.ProfileSite.Web.Permalink", "Permalink", b1 =>
                        {
                            b1.Property<Guid>("PostId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Month")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Slug")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Year")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PostId");

                            b1.ToTable("Posts");

                            b1.WithOwner()
                                .HasForeignKey("PostId");
                        });

                    b.Navigation("Permalink")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
